### ISSUE TITLE
correct symbols on Opt-Cruz comparison

### ISSUE THREAD

**Issue by kelle** [elliesch/NIRSpecFigures#1]
Regarding this figure: https://github.com/elliesch/NIRSpecFigures/blob/master/plots/opt_field_obj.pdf

I went through [OptNIR All spreadsheet](https://docs.google.com/spreadsheets/d/1J19x7ke7I28NIqAch66yRfkTNF7LIWEMklvLWyRg9MQ/edit#gid=0) used to generate this figure to identify the 6 outliers.
![screen shot 2017-03-17 at 1 21 06 pm](https://cloud.githubusercontent.com/assets/1444249/24054743/a06d0572-0b13-11e7-9888-2d5dec84953f.png)

If I understand everything right, I found a couple problems: 
-  object 5 is 2252-17, has an optical type of L5 and a Cruz type of L8pec. That means it should be a star (difference in peculiarity), right? not a circle?
- object 6 is 2148+4003 and has an optical type of L6 and a Cruz NIR type of L4gamma pec. It should not be a diamond (difference in blueness) but either a star (difference in pec) or some other symbol for difference in gravity.

These two things makes me think there may be a bug in going from the spreadsheet to the figure.

**Comment by elliesch** [comment]
So far it seems that the bug is only in the Cruz vs. Optical plot. Object 5 was an error on my part, but Object 6 is a bug in the code. I don't know why it's doing this yet, but I will post here when I do.

**Comment by elliesch** [comment]
I found the bug and I fixed the plots! It was reading the color differences incorrectly when the spectral types had no difference in blueness. The updated plots are commit c737f03bc03f4146e9b516d55cac730bec2ea47a.
